// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SwiftGame.Data;

#nullable disable

namespace SwiftGame.Data.SqlServer.Migrations;

[DbContext(typeof(SwiftGameDbContext))]
[Migration("20260410091642_GuestPlayerFixedId")]
partial class GuestPlayerFixedId
{
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "10.0.5")
            .HasAnnotation("Relational:MaxIdentifierLength", 128);

        SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

        modelBuilder.Entity("SwiftGame.Data.Entities.Player", b =>
            {
                b.Property<Guid>("Id")
                    .HasColumnType("uniqueidentifier");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("datetime2");

                b.Property<string>("Email")
                    .IsRequired()
                    .HasMaxLength(255)
                    .HasColumnType("nvarchar(255)");

                b.Property<string>("Username")
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnType("nvarchar(50)");

                b.HasKey("Id");

                b.HasIndex("Email")
                    .IsUnique();

                b.HasIndex("Username")
                    .IsUnique();

                b.ToTable("Players");
            });

        modelBuilder.Entity("SwiftGame.Data.Entities.Score", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uniqueidentifier");

                b.Property<bool>("IsCorrect")
                    .HasColumnType("bit");

                b.Property<DateTime>("PlayedAt")
                    .HasColumnType("datetime2");

                b.Property<Guid>("PlayerId")
                    .HasColumnType("uniqueidentifier");

                b.Property<int>("PointsEarned")
                    .HasColumnType("int");

                b.Property<int>("ResponseTimeMs")
                    .HasColumnType("int");

                b.Property<Guid>("SongId")
                    .HasColumnType("uniqueidentifier");

                b.HasKey("Id");

                b.HasIndex("PlayerId");

                b.HasIndex("SongId");

                b.ToTable("Scores");
            });

        modelBuilder.Entity("SwiftGame.Data.Entities.Song", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uniqueidentifier");

                b.Property<string>("Album")
                    .IsRequired()
                    .HasMaxLength(200)
                    .HasColumnType("nvarchar(200)");

                b.Property<string>("AlbumArt")
                    .IsRequired()
                    .HasMaxLength(500)
                    .HasColumnType("nvarchar(500)");

                b.Property<string>("ArtistName")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("nvarchar(100)");

                b.Property<int>("DurationMs")
                    .HasColumnType("int");

                b.Property<string>("PreviewUrl")
                    .HasMaxLength(500)
                    .HasColumnType("nvarchar(500)");

                b.Property<string>("Provider")
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnType("nvarchar(50)");

                b.Property<string>("ProviderId")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("nvarchar(100)");

                b.Property<int>("ReleaseYear")
                    .HasColumnType("int");

                b.Property<string>("Title")
                    .IsRequired()
                    .HasMaxLength(200)
                    .HasColumnType("nvarchar(200)");

                b.HasKey("Id");

                b.HasIndex("ProviderId", "Provider")
                    .IsUnique();

                b.ToTable("Songs");
            });

        modelBuilder.Entity("SwiftGame.Data.Entities.Score", b =>
            {
                b.HasOne("SwiftGame.Data.Entities.Player", "Player")
                    .WithMany("Scores")
                    .HasForeignKey("PlayerId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.HasOne("SwiftGame.Data.Entities.Song", "Song")
                    .WithMany("Scores")
                    .HasForeignKey("SongId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();

                b.Navigation("Player");

                b.Navigation("Song");
            });

        modelBuilder.Entity("SwiftGame.Data.Entities.Player", b =>
            {
                b.Navigation("Scores");
            });

        modelBuilder.Entity("SwiftGame.Data.Entities.Song", b =>
            {
                b.Navigation("Scores");
            });
#pragma warning restore 612, 618
    }
}
